apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hello-world 
  namespace: default
  labels:
    app:  hello-world 
spec:
  selector:
    matchLabels:
      app: hello-world 
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  hello-world
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  hello-world 
        image:  rancher/hello-world
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 500Mi
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:   open-liberty
  namespace: default
  labels:
    app:   open-liberty
spec:
  selector:
    matchLabels:
      app:  open-liberty
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  open-liberty
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:   openliberty 
        image:   openliberty/open-liberty
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
        - containerPort: 80
      restartPolicy: Always